# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = UILib
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"$(OutputPath)" \
    -L"../TestStaticLibrary/debug" \
    -L"$(NOINHERIT)" \
    -lTestStaticLibrary \
    -lshell32
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(UILib.pri)
TRANSLATIONS += Translation_ja_JP.ts
